name: Export projects to HTML5 and deploy to S3 bucket
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.1

jobs:
  export-html5:
    name: Export projects to HTML5 and deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          npm install && npm run build && aws s3 sync ./out s3://${{secrets.AWS_BUCKET_NAME}}/simple-sweet/pour --delete
